<?php

/**
 * Implements hook_theme().
 */
function blocks_theme() {
  return array(
    'villes_slider' => array(
      'template' => 'themes/villes_slider'
    ),
    'accroches' => array(
      'template' => 'themes/accroches'
    ),
    'last_announcements' => array(
      'template' => 'themes/last_announcements'
    ),
    'footer' => array(
      'template' => 'themes/footer'
    ),
    'txt_referencement' => array(
      'template' => 'themes/txt_referencement'
    ),
    'sidebar_filters' => array(
      'template' => 'themes/sidebar_filters'
    ),
    'sidebar_pub' => array(
      'template' => 'themes/sidebar_pub'
    ),
    'tableau_de_bord' => array(
      'template' => 'themes/tableau_de_bord'
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function blocks_block_info() {
  $blocks = array();
  $blocks['vam_villes_slider'] = array(
    'info' => t('VAM Villes slider'),
    //'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['vam_accroches'] = array(
    'info' => t('VAM Accroches'),
      //'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['vam_last_announcements'] = array(
    'info' => t('VAM Last announcements'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['vam_footer'] = array(
    'info' => t('VAM Footer'),
      //'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['vam_referencement'] = array(
    'info' => t('VAM texte Referencement bas page'),
      //'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['vam_sidebar_filters'] = array(
    'info' => t('VAM Les filters du sidebar'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['vam_sidebar_pub'] = array(
    'info' => t('VAM Sidebar pub 300x250'),
      //'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['vam_tableau_de_bord'] = array(
    'info' => t('VAM Tableau de bord'),
      //'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function blocks_block_view($block_name = '') {
  global $theme_path, $user;

  switch ($block_name) {
    case 'vam_villes_slider':
      $query = new EntityFieldQuery();
      $entities = $query->entityCondition('entity_type', 'taxonomy_term')
          ->propertyCondition('vid', 2)
          ->fieldCondition('field_show_in_front', 'value', 1)
          ->fieldCondition('field_image', 'fid', '', '!=')
          ->propertyOrderBy('weight')
          ->execute();

      $content = theme('villes_slider', array('villes' => $entities['taxonomy_term']));
      break;
    case 'vam_accroches':
      $content = theme('accroches');
      break;
    case 'vam_last_announcements':
      $content = theme('last_announcements');
      break;
    case 'vam_footer':
      $villes = db_query('SELECT COUNT(field_ville_tid) total, field_ville_tid tid FROM vam_field_data_field_ville GROUP BY field_ville_tid HAVING COUNT(field_ville_tid) > 3 ORDER BY total DESC LIMIT 20')
          ->fetchAll();
      $content = theme('footer', array('villes' => $villes));
      break;
    case 'vam_referencement':
      $content = theme('txt_referencement');
      break;
    case 'vam_sidebar_filters':
      $content = theme('sidebar_filters');
      break;
    case 'vam_sidebar_pub':
      $content = theme('sidebar_pub');
      break;
    case 'vam_tableau_de_bord':
      $user = user_load($user->uid);
      $user_name = $user->field_civilite['und'][0]['value'] . ' ' . strtoupper($user->field_nom['und'][0]['value']) . ' ' . ucwords($user->field_prenom['und'][0]['value']);
      $content = theme('tableau_de_bord', array('theme_path' => $theme_path, 'user_name' => $user_name));
      break;
  }

  $block = array(
    'subject' => null,
    'content' => $content,
  );

  return $block;
}

?>
