<?php

/**
 * Implements hook_theme().
 */
function blocks_theme() {
  return array(
    'villes_slider' => array(
      'template' => 'themes/villes_slider'
    ),
    'accroches' => array(
      'template' => 'themes/accroches'
    ),
    'last_announcements' => array(
      'template' => 'themes/last_announcements'
    ),
    'footer' => array(
      'template' => 'themes/footer'
    ),
    'txt_referencement' => array(
      'template' => 'themes/txt_referencement'
    ),
    'sidebar_filters' => array(
      'template' => 'themes/sidebar_filters'
    ),
    'sidebar_pub' => array(
      'template' => 'themes/sidebar_pub'
    ),
    'tableau_de_bord' => array(
      'template' => 'themes/tableau_de_bord'
    ),
    'front_search' => array(
      'template' => 'themes/front_search'
    ),
  );
}

/**
 * Implements hook_block_info().
 */
function blocks_block_info() {
  $blocks = array();
  $blocks['vam_villes_slider'] = array(
    'info' => t('VAM Villes slider'),
      //'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['vam_accroches'] = array(
    'info' => t('VAM Accroches'),
      //'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['vam_last_announcements'] = array(
    'info' => t('VAM Last announcements'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['vam_footer'] = array(
    'info' => t('VAM Footer'),
      //'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['vam_referencement'] = array(
    'info' => t('VAM texte Referencement bas page'),
      //'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['vam_sidebar_filters'] = array(
    'info' => t('VAM Les filters du sidebar'),
    'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['vam_sidebar_pub'] = array(
    'info' => t('VAM Sidebar pub 300x250'),
      //'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['vam_tableau_de_bord'] = array(
    'info' => t('VAM Tableau de bord'),
      //'cache' => DRUPAL_NO_CACHE,
  );
  $blocks['vam_front_search'] = array(
    'info' => t('VAM Front Search'),
      //'cache' => DRUPAL_NO_CACHE,
  );
  return $blocks;
}

/**
 * Implements hook_block_view().
 */
function blocks_block_view($block_name = '') {
  global $theme_path, $user;

  switch ($block_name) {
    case 'vam_villes_slider':
      $query = new EntityFieldQuery();
      $entities = $query->entityCondition('entity_type', 'taxonomy_term')
          ->propertyCondition('vid', 2)
          ->fieldCondition('field_show_in_front', 'value', 1)
          ->fieldCondition('field_image', 'fid', '', '!=')
          ->propertyOrderBy('weight')
          ->execute();

      $content = theme('villes_slider', array('villes' => $entities['taxonomy_term']));
      break;
    case 'vam_accroches':
      $content = theme('accroches');
      break;
    case 'vam_last_announcements':
      $query = new EntityFieldQuery();
      $entities = $query->entityCondition('entity_type', 'node')
          ->entityCondition('bundle', 'annonce')
          ->propertyCondition('status', 1)
          ->fieldCondition('field_photos', 'fid', '', '!=')
          ->propertyOrderBy('created', 'DESC')
          ->range(0, 8)
          ->execute();
      $nodes = node_load_multiple(array_keys($entities['node']));
      $query = new EntityFieldQuery();
      $entities = $query->entityCondition('entity_type', 'node')
              ->entityCondition('bundle', 'annonce')
              ->propertyCondition('status', 1)
              ->count()->execute();
      $content = theme('last_announcements', array('nodes' => $nodes, 'total' => $entities));
      break;
    case 'vam_footer':
      $villes = db_query('SELECT COUNT(field_ville_tid) total, field_ville_tid tid FROM vam_field_data_field_ville GROUP BY field_ville_tid HAVING COUNT(field_ville_tid) > 3 ORDER BY total DESC LIMIT 20')
          ->fetchAll();
      $content = theme('footer', array('villes' => $villes));
      break;
    case 'vam_referencement':
      $content = theme('txt_referencement');
      break;
    case 'vam_sidebar_filters':
      $content = theme('sidebar_filters');
      break;
    case 'vam_sidebar_pub':
      $content = theme('sidebar_pub');
      break;
    case 'vam_tableau_de_bord':
      $user = user_load($user->uid);
      $user_name = $user->field_civilite['und'][0]['value'] . ' ' . strtoupper($user->field_nom['und'][0]['value']) . ' ' . ucwords($user->field_prenom['und'][0]['value']);
      $content = theme('tableau_de_bord', array('theme_path' => $theme_path, 'user_name' => $user_name, 'user' => $user));
      break;
    case 'vam_front_search' :
      $content = theme('front_search', array('search_form' => drupal_get_form('search_form')));
      break;
  }

  $block = array(
    'subject' => null,
    'content' => $content,
  );

  return $block;
}

function search_form() {
  $form = array();
  $form['quick_search'] = array(
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );
  $form['advanced_search'] = array(
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );
  $form['quick_search']['type_de_bien'] = array(
    '#type' => 'select',
    '#title' => 'Type de logement',
    '#required' => FALSE,
    '#options' => load_select_from_tax(3, TRUE),
      //'#default_value' => ,
  );
  $form['quick_search']['ville'] = array(
    '#type' => 'select',
    '#title' => 'Situé à',
    '#required' => FALSE,
    '#options' => load_select_from_tax(2, TRUE),
      //'#default_value' => ,
  );
  $form['quick_search']['prix_nuitee_max'] = array(
    '#type' => 'textfield',
    '#title' => 'Prix nuitée max <span class="dhs">en DHS</span>',
    '#maxlength' => 10,
    '#size' => 25,
    '#required' => FALSE,
    '#attributes' => array('onfocus' => "if (this.value == 'ex: 350') {this.value = ''; }", 'onblur' => "if (this.value == ''){this.value = 'ex: 350'; }", 'value' => 'ex: 350'),
      //'#default_value' => ,
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#prefix' => '<div id="front-search-button">',
    '#value' => ('Rechercher'),
    '#suffix' => '</div>',
    '#attributes' => array('class' => array('custom-submitt-button')),
  );

  /* $form['quick_search'] = array(
    '#type' => 'radios',
    '#title' => t('Vous êtes'),
    '#required' => TRUE,
    '#options' => load_select_from_tax(4),
    //'#default_value' => ,
    );
    $form['email'] = array(
    '#type' => 'textfield',
    '#title' => ('E-mail'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
    //'#default_value' => ,
    );
    $form['informations_contact'] = array(
    '#markup' => '<h3 class="top-20">Informations de contact</h3>',
    );
    $form['civilite'] = array(
    '#type' => 'radios',
    '#title' => t('Civilité'),
    '#required' => TRUE,
    '#options' => array('Mr' => 'Mr', 'Mme' => 'Mme'),
    //'#default_value' => ,
    );
    $form['nom'] = array(
    '#type' => 'textfield',
    '#title' => t('Nom'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
    //'#default_value' => ,
    );
    $form['prenom'] = array(
    '#type' => 'textfield',
    '#title' => t('Prénom'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
    //'#default_value' => ,
    );
    $form['tel'] = array(
    '#type' => 'textfield',
    '#title' => t('Tél.'),
    '#size' => 20,
    '#maxlength' => 20,
    '#required' => TRUE,
    //'#default_value' => ,
    );

    $form['agence'] = array(
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
    );

    $form['agence']['informations_agence'] = array(
    '#markup' => '<h3 class="top-20">Informations agence</h3>',
    );
    $form['agence']['nom_agence'] = array(
    '#type' => 'textfield',
    '#title' => ('Nom de l\'agence <span title="Ce champ est obligatoire." class="form-required">*</span>'),
    '#size' => 60,
    '#maxlength' => 128,
    '#attributes' => array('class' => array('required')),
    //'#default_value' => ,
    );
    $form['agence']['ville_agence'] = array(
    '#type' => 'select',
    '#title' => ('Ville <span title="Ce champ est obligatoire." class="form-required">*</span>'),
    '#options' => load_select_from_tax(2, TRUE),
    '#attributes' => array('class' => array('required')),
    //'#default_value' => ,
    );
    $form['agence']['adresse_agence'] = array(
    '#type' => 'textfield',
    '#title' => t('Adresse'),
    '#size' => 60,
    '#maxlength' => 128,
    //'#default_value' => ,
    );
    $form['agence']['cp_agence'] = array(
    '#type' => 'textfield',
    '#title' => t('Code postal'),
    '#size' => 20,
    '#maxlength' => 11,
    //'#default_value' => ,
    );
    $form['agence']['tel_agence'] = array(
    '#type' => 'textfield',
    '#title' => ('Téléphone <span title="Ce champ est obligatoire." class="form-required">*</span>'),
    '#size' => 20,
    '#maxlength' => 20,
    '#attributes' => array('class' => array('required')),
    //'#default_value' => ,
    );
    $form['agence']['site_web_agence'] = array(
    '#type' => 'textfield',
    '#title' => t('Site web'),
    '#size' => 60,
    '#maxlength' => 128,
    //'#default_value' => ,
    );

    $form['agence']['logo_agence'] = array(
    '#type' => 'file',
    '#title' => t('Logo'),
    '#size' => 35,
    '#attributes' => array('class' => array('has-description')),
    '#required' => FALSE,
    '#description' => 'Formats autorisés : JPG, JPEG, PNG ou GIF',
    );
    $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Envoyé'),
    '#attributes' => array('class' => array('custom-submitt-button top-20')),
    ); */
  return $form;
}

function search_form_validate($form, &$form_state) {
  
}

function search_form_submit($form, &$form_state) {
  module_load_include('inc', 'pathauto');
  $values = $form_state['values'];

  //Quick search
  $url = 'locations-vacances-maroc';
  $options = array();
  if (!empty($values['ville'])) {
    $ville = pathauto_cleanstring(taxonomy_term_load($values['ville'])->name);
    if (!empty($ville))
      $url .= '/' . $ville;
  }
  if (!empty($values['type_de_bien'])) {
    $type_de_bien = pathauto_cleanstring(taxonomy_term_load($values['type_de_bien'])->name);
    if (!empty($type_de_bien))
      $url .= '/' . $type_de_bien;
  }
  if (!empty($values['prix_nuitee_max']) && $values['prix_nuitee_max'] != 'ex: 350') {
    $options['prix-max'] = $values['prix_nuitee_max'];
  }

  drupal_goto($url, array('query' => $options));
}

?>
