<?php

/**
 * Implements hook_menu().
 */
function annonces_menu() {
  $items['locations-vacances-maroc'] = array(
    'title' => 'Locations vacances au Maroc',
    'page callback' => 'locations_vacances',
    'access callback' => TRUE,
  );

  $items['locations-vacances-maroc/%/%'] = array(
    'page callback' => 'locations_vacances_recherche',
    'access callback' => TRUE,
  );


  $items['deposer-une-annonce'] = array(
    'title' => 'Déposer une annonce',
    'page callback' => 'deposer_annonce',
    'access callback' => TRUE,
  );

  $items['ajax-set-annonce-picture'] = array(
    'page callback' => 'ajax_set_annonce_picture',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_theme().
 */
function annonces_theme() {
  return array(
    'listing_annonces' => array(
      'template' => 'themes/listing_annonces'
    ),
    'deposer_annonce' => array(
      'template' => 'themes/deposer_annonce'
    ),
  );
}

function locations_vacances($option = array()) {
  global $theme_path;

  $breadcrumb = drupal_get_breadcrumb();

  if (empty($breadcrumb[1]))
    $breadcrumb[] = empty($option) ? 'Locations vacances Maroc' : l('Locations vacances Maroc', 'locations-vacances-maroc');
  if (!empty($option['ville']['breadcrumb'])) {
    $breadcrumb[] = 'Villes';
    $breadcrumb[] = $option['ville']['breadcrumb'];
  }
  if (!empty($option['bien']['breadcrumb'])) {
    $breadcrumb[] = 'Logements';
    $breadcrumb[] = $option['bien']['breadcrumb'];
  }
  drupal_set_breadcrumb($breadcrumb);

  drupal_add_css($theme_path . '/css/inner.css');

  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', 'annonce')
      ->propertyCondition('status', 1)
      ->propertyOrderBy('created', 'DESC')
      ->pager(10);

  if (!empty($option['ville']['tid'])) {
    $query->fieldCondition('field_ville', 'tid', $option['ville']['tid']);
  }
  if (!empty($option['bien']['tid'])) {
    $query->fieldCondition('field_type_du_bien', 'tid', $option['bien']['tid']);
  }

  $entities = $query->execute();

  $nodes = node_load_multiple(@array_keys(@$entities['node']));

  $output = theme('listing_annonces', array('nodes' => $nodes, 'total' => $query->pager['total']));
  $output .= theme('pager', array('tags' => array()));
  return $output;
}

function ajax_set_annonce_picture() {

  echo '<pre><div>';
  print_r($_FILES);
  echo '<br>';
  print_r($_POST);
  echo '</pre>';
  die('DEBUG MODE');
}

function deposer_annonce() {

  $form = null;

  if (user_is_logged_in()) {
    global $theme_path;

    drupal_add_js($theme_path . '/js/ajaxfileupload.js');
    drupal_add_js($theme_path . '/js/jquery.filestyle.js');
    drupal_add_js($theme_path . '/js/jquery.validate.min.js');
    drupal_add_js($theme_path . '/js/messages_fr.js');
    $js = 'jQuery(function($){
          
$("#edit-photo").live("change", function(){

alert($("#edit-photo").val());

    $.ajaxFileUpload({
    
        url:"' . url('ajax-set-annonce-picture') . '",
        secureuri:false,
        fileElementId:"edit-photo",
        dataType: "html",
        
        success: function (data) {
           alert(data);
        },
        error: function (data, status, e){
        
           alert(e);
        }
    })
		
});
            
            $("#nouvelle-annonce").validate({
              errorClass: "invalid",
              validClass: "",
             
              rules: {
               
                },
              messages: {

               }
            });
            
            $("#edit-photo").filestyle({ 
              image: "' . $theme_path . '/images/choose-file.gif",
              imageheight : 35,
              imagewidth : 82,
              width : 250
            });
            
          });';

    drupal_add_js($js, 'inline');
    $form = drupal_get_form('nouvelle_annonce');
  }

  return theme('deposer_annonce', array('nouvelle_annonce' => $form));
}

/**
 * Implementation of hook_query_TAG_alter
 */
function annonces_query_random_alter($query) {
  $query->orderRandom();
}

function get_annonces_par_ville($tid, $nbr) {

  $query = new EntityFieldQuery();
  $entities = $query->entityCondition('entity_type', 'node')
      ->entityCondition('bundle', 'annonce')
      ->propertyCondition('status', 1)
      ->fieldCondition('field_ville', 'tid', $tid)
      ->addTag('random')
      ->range(0, $nbr)
      ->execute();

  $nodes = node_load_multiple(array_keys($entities['node']));
  return $nodes;
}

function get_count_annonces_par_ville($tid) {
  $count = db_query('SELECT COUNT(field_ville_tid) total FROM vam_field_data_field_ville WHERE field_ville_tid = :tid', array(':tid' => $tid))
      ->fetch();
  return $count->total;
}

function locations_vacances_taxonomy_redirect() {
  $option = array();
  $term = taxonomy_term_load(arg(2));
  if (isset($term->vocabulary_machine_name)) {
    switch ($term->vocabulary_machine_name) {
      case 'villes':
        $option['ville']['breadcrumb'] = $term->name;
        $option['ville']['tid'] = $term->tid;
        break;
      case 'type_du_bien':
        $option['bien']['breadcrumb'] = $term->name;
        $option['bien']['tid'] = $term->tid;
        break;
    }
  }else
    drupal_not_found();

  return locations_vacances($option);
}

function locations_vacances_recherche() {
  for ($i = 1; $i <= 2; $i++) {
    $term = current(taxonomy_get_term_by_name(str_replace('-', ' ', arg($i))));
    if (isset($term->vocabulary_machine_name)) {
      switch ($term->vocabulary_machine_name) {
        case 'villes':
          $option['ville']['breadcrumb'] = $term->name;
          $option['ville']['tid'] = $term->tid;
          break;
        case 'type_du_bien':
          $option['bien']['breadcrumb'] = $term->name;
          $option['bien']['tid'] = $term->tid;
          break;
      }
    }else
      drupal_not_found();
  }
  drupal_set_title($option['ville']['breadcrumb'] . ' » ' . $option['bien']['breadcrumb']);
  return locations_vacances($option);
}

/**
  Déposer une annonce functions
 * 
 */
function nouvelle_annonce() {
  $form = array();
  $form['informations_logement'] = array(
    '#markup' => '<h3>Informations sur le logement</h3>',
  );

  $form['title'] = array(
    '#type' => 'textfield',
    '#title' => ('Titre de l\'annonce'),
    '#size' => 60,
    '#maxlength' => 60,
    '#required' => TRUE,
  );
  $form['photos'] = array(
    '#markup' => '<h3 class="top-20">Photos</h3>',
  );


  $form['photo'] = array(
    '#type' => 'file',
    '#title' => t('Ajouter une photo'),
    '#attributes' => array('class' => array('has-description')),
    '#required' => FALSE,
    '#size' => FALSE,
    '#description' => 'Formats autorisés : JPG, JPEG, PNG ou GIF',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Envoyé'),
    '#attributes' => array('class' => array('custom-submitt-button top-20')),
  );
  return $form;
}

function nouvelle_annonce_validate($form, &$form_state) {
  
}

function nouvelle_annonce_submit($form, &$form_state) {
  $data = $form_state['values'];
  echo '<pre>';
  print_r($form_state['values']);
  print '<br>';
  print_r($_FILES);
  echo '</pre>';
  die('DEBUG MODE');
}