<?php

function mon_compte_init() {
  $arg1 = arg(1);
  if (arg(0) == "user" && empty($arg1) && user_is_logged_in()) {
    drupal_goto('annonces-manager');
  }
}

/**
 * Implements hook_menu().
 */
function mon_compte_menu() {
  $items['inscription'] = array(
    'title' => 'Inscription',
    'page callback' => 'inscription',
    'access callback' => TRUE,
  );

  $items['inscription/succes'] = array(
    'title' => 'Inscription réussite avec succès',
    'page callback' => 'inscription_succes',
    'access callback' => TRUE,
  );

  $items['annonces-manager'] = array(
    'title' => 'Mes annonces management',
    'page callback' => 'annonces_manager',
    'access callback' => 'user_is_logged_in',
    'file' => 'annonces.manager.inc',
  );
  $items['modifier-mes-coordonnees'] = array(
    'title' => 'Modifier mes coordonnées',
    'page callback' => 'modifier_mes_coordonnees',
    'access callback' => 'user_is_logged_in',
    'file' => 'compte.fo.inc',
  );
  return $items;
}

/**
 * Implements hook_theme().
 */
function mon_compte_theme() {
  return array(
    'inscription' => array(
      'template' => 'themes/inscription'
    ),
    'annonces_manager' => array(
      'template' => 'themes/annonces_manager'
    ),
    'inscription_succes' => array(
      'template' => 'themes/inscription_succes'
    ),
    'mes_coordonnees' => array(
      'template' => 'themes/mes_coordonnees'
    ),
  );
}

/**
 * Implements hook_form_alter().
 * @author BENSLIMANE Med Amine
 * @param array $form Form array
 * @param array $form_state Form values array
 * @param string $form_id Form ID
 */
function mon_compte_form_alter(&$form, &$form_state, $form_id) {

  switch ($form_id) {
    case 'user_login' :

      unset($form['name']['#description']);
      unset($form['pass']['#description']);
      $form['name']['#title'] = 'E-mail';
      $form['actions']['#suffix'] = '<p class="normal">' . l('&rarr; Créer un nouveau compte', 'inscription', array('html' => TRUE)) . '</p>';
      $form['actions']['#suffix'] .= '<p class="normal">' . l('&rarr; Vous avez oublié votre mot de passe ?', 'user/password', array('html' => TRUE)) . '</p>';

      break;
    case 'user_pass' :

      $form['name']['#title'] = 'E-mail';
      $form['name']['#description'] = 'Vous avez perdu votre mot de passe? Il vous suffit de saisir votre adresse e-mail d\'inscription. Vous recevrez un e-mail contenant un lien vous permettant de changer votre mot de passe.';

      break;
  }
}

function inscription() {
  global $theme_path;
  drupal_add_js($theme_path.'/js/messages_fr.js');
  drupal_add_js($theme_path . '/js/jquery.filestyle.js');
  drupal_add_js($theme_path . '/js/jquery.validate.min.js');
  drupal_add_js($theme_path . '/js/messages_fr.js');
  $js = 'jQuery(function($){

            //Costum validators
            $.validator.addMethod("check_ext_photo", function(value, element) {
              var ext = value.split(".").pop().toLowerCase();
              var check = ($.inArray(ext, ["gif","png","jpg","jpeg"]) == -1) ? false : true;
              return this.optional(element) || check;
            }, "L\'extension de la photo est non valide.");

            $("#edit-agence").hide();
            $(".form-item-type-annonceur input").live("click", function() {
              if($(this).val() == 58){
                $("#edit-agence").show();
              }else
                $("#edit-agence").hide();
            });

            if ($("input[name=type_annonceur]:checked").val() == 58){
              $("#edit-type-annonceur-58").trigger("click");
            }

            $("#inscription-form").validate({
              errorClass: "invalid",
              validClass: "",
              errorPlacement: function(error, element) {
                if (element.attr("name") == "type_annonceur" || element.attr("name") == "civilite" || element.attr("name") == "files[logo_agence]" )
                  error.appendTo( element.parent("div").parent("div") );
                else
                  error.insertAfter(element);
              },
              rules: {
                  type_annonceur: "required",
                  civilite: "required",
                  email: {
                    required: true,
                    email: true
                  },
                  tel: "digits",
                  cp_agence: "digits",
                  tel_agence: "digits",
                  site_web_agence: "url",
                  "files[logo_agence]": "check_ext_photo"
                },
              messages: {

               }
            });
            $("#edit-logo-agence").filestyle({
              image: "'.$theme_path.'/images/choose-file.gif",
              imageheight : 35,
              imagewidth : 82,
              width : 250
            });          });';

  drupal_add_js($js, 'inline');
  return theme('inscription', array('form' => drupal_get_form('inscription_form')));
}

function inscription_form() {
  $form = array();
  $form['informations_d_identification'] = array(
    '#markup' => '<h3>Informations d’identification</h3>',
  );
  $form['type_annonceur'] = array(
    '#type' => 'radios',
    '#title' => t('Vous êtes'),
    '#required' => TRUE,
    '#options' => load_select_from_tax(4),
      //'#default_value' => ,
  );
  $form['email'] = array(
    '#type' => 'textfield',
    '#title' => ('E-mail'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
      //'#default_value' => ,
  );
  $form['informations_contact'] = array(
    '#markup' => '<h3 class="top-20">Informations de contact</h3>',
  );
  $form['civilite'] = array(
    '#type' => 'radios',
    '#title' => t('Civilité'),
    '#required' => TRUE,
    '#options' => array('Mr' => 'Mr', 'Mme' => 'Mme'),
      //'#default_value' => ,
  );
  $form['nom'] = array(
    '#type' => 'textfield',
    '#title' => t('Nom'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
      //'#default_value' => ,
  );
  $form['prenom'] = array(
    '#type' => 'textfield',
    '#title' => t('Prénom'),
    '#size' => 60,
    '#maxlength' => 128,
    '#required' => TRUE,
      //'#default_value' => ,
  );
  $form['tel'] = array(
    '#type' => 'textfield',
    '#title' => t('Tél.'),
    '#size' => 20,
    '#maxlength' => 20,
    '#required' => TRUE,
      //'#default_value' => ,
  );

  $form['agence'] = array(
    '#type' => 'fieldset',
    '#collapsible' => FALSE,
    '#collapsed' => FALSE,
  );

  $form['agence']['informations_agence'] = array(
    '#markup' => '<h3 class="top-20">Informations agence</h3>',
  );
  $form['agence']['nom_agence'] = array(
    '#type' => 'textfield',
    '#title' => ('Nom de l\'agence <span title="Ce champ est obligatoire." class="form-required">*</span>'),
    '#size' => 60,
    '#maxlength' => 128,
    '#attributes' => array('class' => array('required')),
      //'#default_value' => ,
  );
  $form['agence']['ville_agence'] = array(
    '#type' => 'select',
    '#title' => ('Ville <span title="Ce champ est obligatoire." class="form-required">*</span>'),
    '#options' => load_select_from_tax(2, TRUE),
    '#attributes' => array('class' => array('required')),
      //'#default_value' => ,
  );
  $form['agence']['adresse_agence'] = array(
    '#type' => 'textfield',
    '#title' => t('Adresse'),
    '#size' => 60,
    '#maxlength' => 128,
      //'#default_value' => ,
  );
  $form['agence']['cp_agence'] = array(
    '#type' => 'textfield',
    '#title' => t('Code postal'),
    '#size' => 20,
    '#maxlength' => 11,
      //'#default_value' => ,
  );
  $form['agence']['tel_agence'] = array(
    '#type' => 'textfield',
    '#title' => ('Téléphone <span title="Ce champ est obligatoire." class="form-required">*</span>'),
    '#size' => 20,
    '#maxlength' => 20,
    '#attributes' => array('class' => array('required')),
      //'#default_value' => ,
  );
  $form['agence']['site_web_agence'] = array(
    '#type' => 'textfield',
    '#title' => t('Site web'),
    '#size' => 60,
    '#maxlength' => 128,
      //'#default_value' => ,
  );

  $form['agence']['logo_agence'] = array(
    '#type' => 'file',
    '#title' => t('Logo'),

    '#attributes' => array('class' => array('has-description')),
    '#required' => FALSE,
     '#size' => FALSE,
    '#description' => 'Formats autorisés : JPG, JPEG, PNG ou GIF',
  );
  $form['submit'] = array(
    '#type' => 'submit',
    '#value' => t('Envoyé'),
    '#attributes' => array('class' => array('custom-submitt-button top-20')),
  );
  return $form;
}

function inscription_form_validate($form, &$form_state) {
  $data = $form_state['values'];

  if (!empty($data['email'])) {
    // Validate email
    if (!valid_email_address($data['email'])) {
      form_set_error('email', t('Veuillez saisir une adresse e-mail valide.'));
    }
    // Email existe
    else {
      $user = user_load_by_mail($data['email']);
      if (!empty($user)) {
        form_set_error('email', t('Cette adresse e-mail existe déjà, veuillez saisir une autre adresse e-mail.'));
      }
    }
  }

  // Upload files if any
  if (!empty($_FILES['files']['name']['logo_agence'])) {

    $file = inscription_upload_file('logo_agence', 'public://');

    if (empty($file)) {

      form_set_error('logo_agence', t('Veuillez mettre une photo de type (JPG, JPEG, PNG ou GIF) ayant une taille de 1Mo ou moins.'));
    }
    else {
      $form_state['values']['fid_logo_agence'] = $file->fid;
    }
  }

//  // Upload files if any
//  if (!empty($_FILES['files']['name']['logo_agence'])) {
//    $files = array();
//    foreach ($_FILES['files']['name'] as $k => $v) {
//      if (!empty($v)) {
//        $file = inscription_upload_file($k, 'public://');
//
//        if (empty($file)) {
//          form_set_error($k, t('Veuillez mettre une photo de type (jpg, jpeg) ayant une taille de 200Ko ou moins.'));
//        }
//        else {
//          $files[] = $file;
//        }
//      }
//    }
//
//    if (!empty($files)) {
//      foreach ($files as $k => $v) {
//        $form_state['values']['fid_' . $v->source] = $v->fid;
//      }
//    }
//  }
}

function inscription_form_submit($form, &$form_state) {
  $data = $form_state['values'];


  $pass = user_password();
  $account = array(
    'name' => $data['email'],
    'mail' => $data['email'],
    'init' => $data['email'],
    'pass' => $pass,
    'status' => 1,
    'field_type_annonceur' => array(LANGUAGE_NONE => array(array('tid' => $data['type_annonceur']))),
    'field_civilite' => array(LANGUAGE_NONE => array(array('value' => $data['civilite']))),
    'field_nom' => array(LANGUAGE_NONE => array(array('value' => $data['nom']))),
    'field_prenom' => array(LANGUAGE_NONE => array(array('value' => $data['prenom']))),
    'field_tel' => array(LANGUAGE_NONE => array(array('value' => $data['tel']))),
  );
  //Si l'annonceur est un professionel
  if ($data['type_annonceur'] == 58) {
    $account['field_nom_agence'] = array(LANGUAGE_NONE => array(array('value' => $data['nom_agence'])));
    $account['field_ville'] = array(LANGUAGE_NONE => array(array('tid' => $data['ville_agence'])));
    if (!empty($data['adresse_agence']))
      $account['field_adresse'] = array(LANGUAGE_NONE => array(array('value' => $data['adresse_agence'])));
    if (!empty($data['cp_agence']))
      $account['field_code_postal_agence'] = array(LANGUAGE_NONE => array(array('value' => $data['cp_agence'])));
    $account['field_tel_agence'] = array(LANGUAGE_NONE => array(array('value' => $data['tel_agence'])));
    if (!empty($data['site_web_agence']))
      $account['field_site_web'] = array(LANGUAGE_NONE => array(array('value' => $data['site_web_agence'])));
    if (!empty($data['fid_logo_agence']))
      $account['field_image'] = array(LANGUAGE_NONE => array(array('fid' => $data['fid_logo_agence'])));
  }

  $user = user_save(drupal_anonymous_user(), $account);
  $_SESSION['inscription']['user']['mail'] = $user->mail;
  //TODO: Delete the line bellow
  $_SESSION['inscription']['user']['pass'] = $pass;
  drupal_goto('inscription/succes');
}

function inscription_succes() {

  $mail = $_SESSION['inscription']['user']['mail'];

  if (empty($mail)) {
    drupal_goto('inscription');
  }
  unset($_SESSION['inscription']['user']['mail']);
  //TODO: Delete the edit bellow
  return theme('inscription_succes', array('mail' => $mail, 'pass' => $_SESSION['inscription']['user']['pass']));
}

function inscription_upload_file($file, $savepath) {
  $limits = array();


  $limits['extensions'] = array('jpg jpeg gif png');
  $limits['file_size'] = 2000 * 1024;

  $validators = array(
    'file_validate_extensions' => $limits['extensions'],
    'file_validate_size' => array(
      $limits['file_size']
    ),
  );

  $file = file_save_upload($file, $validators, $savepath);

  return $file;
}

?>
