<?php

/**
 * Implements hook_menu().
 */
function mon_compte_menu() {
  $items['inscription'] = array(
    'title' => 'Inscription',
    'page callback' => 'inscription',
    'access callback' => TRUE,
  );

  return $items;
}

/**
 * Implements hook_form_alter().
 * @author BENSLIMANE Med Amine
 * @param array $form Form array
 * @param array $form_state Form values array
 * @param string $form_id Form ID
 */
function mon_compte_form_alter(&$form, &$form_state, $form_id) {
  global $user;
  switch ($form_id) {
    case 'user_login' :

      unset($form['name']['#description']);
      unset($form['pass']['#description']);
      $form['name']['#title'] = 'E-mail';
      $form['actions']['#suffix'] = '<p class="normal">' . l('&rarr; Créer un nouveau compte', 'inscription', array('html' => TRUE)) . '</p>';
      $form['actions']['#suffix'] .= '<p class="normal">' . l('&rarr; Vous avez oublié votre mot de passe ?', 'user/password', array('html' => TRUE)) . '</p>';

      break;
    case 'user_pass' :

      $form['name']['#title'] = 'E-mail';
      $form['name']['#description'] = 'Vous avez perdu votre mot de passe? Il vous suffit de saisir votre adresse e-mail d\'inscription. Vous recevrez un e-mail contenant un lien vous permettant de changer votre mot de passe.';

      break;
  }
}

function inscription() {

  $node = node_load(1);

  $user_message = t('Check out my latest comment on vacaumaroc.com..');
  $attachment = array(
    'name' => $node->title,
    'href' => url('node/' . $node->nid, array('absolute' => TRUE)),
    'description' => $node->body['und'][0]['value'],
    'properties' => array(t('In reply to') => array('text' => $node->title, 'href' => url("node/" . $node->nid, array('absolute' => TRUE)))),
  );
  $actions = array();
  $actions[] = array(
    'text' => t('Read More'),
    'href' => url('node/' . $a1['nid'], array('absolute' => TRUE))
  );
  
  echo '<pre>';
  //print_r($attachment);
  echo '</pre>';
  
  print fb_stream_publish_dialog(array('user_message' => $user_message,
    'attachment' => $attachment,
    'action_links' => $actions,
  ));
  die('DEBUG MODE');
}

?>
